Full_Identity/Controllers/SchoolController.cs
using Full_Identity.DTOs;
using Full_Identity.Helper;
using IdentityData.AppDbContext;
using IdentityData.Entities;
using IdentityData.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Full_Identity.Controllers;

[Authorize]
public class SchoolController: Controller
{
    private readonly Context _context;
    private readonly UserProvider _userProvider;
    public SchoolController(Context context, UserProvider userProvider)
    {
        _context = context;
        _userProvider = userProvider;
    }
    public async Task<IActionResult> Index()
    {
        var schools = await _context.Schools.Include(i => i.UserSchools)
            .ToListAsync();
        return View(schools);
    }

    [HttpGet]
    public IActionResult CreateSchool()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> CreateSchool(CreateSchoolDTO createSchoolDto)
    {
        var school = new School()
        {
            Name = createSchoolDto.Name,
            Description = createSchoolDto.Description,
        };
        if (createSchoolDto.Photo != null)
        {
            school.PhotoUrl = await FileHelper.SaveSchoolFile(createSchoolDto.Photo);
        }
        school.UserSchools = new List<UserSchool>()
        {
            new UserSchool()
            {
                UserId = _userProvider.UserId,
                Status = UserStatus.Creator
            }
        };
        _context.Schools.Add(school);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }
    public async Task<IActionResult> GetSchoolById(Guid id)
        {
            var schoolId = await _context.Schools.
                Include(i=>i.UserSchools).
                ThenInclude(i=>i.User).
                FirstOrDefaultAsync(i => i.Id == id);
                
            return View(schoolId);
        }
    public async Task<IActionResult> JoinSchool(Guid id)
    {
        var userId =  _userProvider.UserId;
        var school = await _context.Schools.
            Include(i => i.UserSchools)
            .ThenInclude(i => i.User).
                FirstOrDefaultAsync(i => i.Id == id);
        var exist = school.UserSchools.Any(i => i.User.Id == userId);
        if (!exist)
        {
            school.UserSchools.Add(new UserSchool()
            {
                UserId = userId,
                Status = UserStatus.Student
            });
        }
        await _context.SaveChangesAsync();
        return RedirectToAction("GetSchoolById", new { school.Id });
    }

    [HttpGet]
    public async Task<IActionResult> UpdateSchool(Guid Id)
    {
        var school = await _context.Schools.
            FirstOrDefaultAsync(i => i.Id == Id);

        ViewBag.Id = Id;
        return View(new UpdataScoolDTO()
        {
            Name = school.Name,
            Description = school.Description,
        });
    }
    [HttpPost]
    public async Task<IActionResult> UpdateSchool(Guid Id,[FromForm] UpdataScoolDTO updataScoolDto)
    {
        var school = await _context.Schools. 
            FirstOrDefaultAsync(i => i.Id == Id);
        school.Name = updataScoolDto.Name;
        school.Description = updataScoolDto.Description;

        if (updataScoolDto.Photo != null)
        {
            school.PhotoUrl = await FileHelper.SaveSchoolFile(updataScoolDto.Photo);
        }
        
        await _context.SaveChangesAsync();
        return RedirectToAction("GetSchoolById", new { id=Id });
    }

    public async Task<IActionResult> UpdateRole(Guid schoolId,Guid userId, UserStatus status)
    {
        var schoolRole = await _context.UserSchools.
            FirstOrDefaultAsync(i => i.SchoolId == schoolId && i.UserId == userId);
        if(schoolRole!.Status != UserStatus.Creator || status != UserStatus.Creator)
            schoolRole!.Status = status;
        await _context.SaveChangesAsync();
        return RedirectToAction("GetSchoolById", new { id = schoolRole.SchoolId });
    }
}

Full_Identity/Controllers/ScienceController.cs
using Full_Identity.DTOs;
using Full_Identity.Helper;
using IdentityData.AppDbContext;
using IdentityData.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Full_Identity.Controllers;

public class ScienceController : Controller
{
    private readonly Context _context;
    private readonly UserProvider _userProvider;

    public ScienceController(Context context, UserProvider userProvider)
    {
        _context = context;
        _userProvider = userProvider;
    }

    public async Task<IActionResult> Index(Guid Id)
    {
     
        var school = await _context.Schools.
            Include(s => s.Sciences!)
            .ThenInclude(o => o.UserSciences).FirstOrDefaultAsync(k => k.Id == Id);
        return View(school);
    }

    [HttpGet]
    public IActionResult CreateScience(Guid Id)
    {
        ViewBag.Id = Id;
        return View();
    } 
    
    [HttpPost]
    public async Task<IActionResult> CreateScience(CreateScienceDTO createScienceDto,Guid schoolId)
    {
        var userId = _userProvider.UserId;
        var science = new Science()
        {
            SchoolId = schoolId,
            Name = createScienceDto.Name,
            Description = createScienceDto.Description,
        };
        
        science.UserSciences = new List<UserScience>()
        {
            new UserScience()
            {
                UserId = userId,
                Type = IdentityData.Enums.UserScience.Teacher,

            }
        };
        _context.Sciences.Add(science);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index",new{ Id = schoolId});
    }

    public async Task<IActionResult> GetScienceById(Guid Id)
    {
        var science = await _context.Sciences
            .Include(i => i.UserSciences)!.
            ThenInclude(i => i.User).
            ThenInclude(t=>t.UserSchools).Include(i=>i.School).
            FirstOrDefaultAsync(i => i.Id == Id);
        
        
        return View(science);
    }
    [HttpGet]
    public async Task<IActionResult> UpdateScience(Guid Id)
    {
        var science = await _context.Sciences.FirstOrDefaultAsync(i => i.Id == Id);
        ViewBag.Id = Id;
        return View(new UpdateScienceDTO()
        {
            Name = science.Name,
            Description = science.Description,
        });
    }

    [HttpPost]
    public async Task<IActionResult> UpdateScience(Guid Id, [FromForm] UpdateScienceDTO updateScienceDto)
    {
        var science =  await _context.Sciences.FirstOrDefaultAsync(i => i.Id == Id);
        science.Name = updateScienceDto.Name;
        science.Description = updateScienceDto.Description;

        await _context.SaveChangesAsync();
        return RedirectToAction("GetScienceById", new { id = science.Id });
    }

    [HttpGet]
    public IActionResult RequestToJoin(Guid Id)
    {
        ViewBag.Id = Id;
        return View();
    }
  [HttpPost]
    public async Task<IActionResult> RequestToJoin(Guid Id, CreateRequestToJoin createRequestToJoin)
    {
        var toUser = await _context.Users.
            FirstOrDefaultAsync(i => i.UserName == createRequestToJoin.Username);
        var isExist = await _context.SendRequestToJoins.
            AnyAsync(i => i.ToUserId ==toUser!.Id  && i.ScienceId == Id);
        if (isExist)
        {
            return RedirectToAction("GetScienceById", new { id = Id });
        }
        var userId = _userProvider.UserId;

        var request = new SendRequestToJoin()
        {
            FromWhomId = userId,
            ScienceId = Id,
            ToUserId = toUser.Id,
            IsJoined = false
        };
        _context.SendRequestToJoins.Add(request);
        await _context.SaveChangesAsync();
        return RedirectToAction("GetScienceById", new { id = Id });
    }

    public async Task<IActionResult> JoinScience(Guid joinRequestId,bool isJoin)
    {
        var joinRequest = await _context.SendRequestToJoins.FirstOrDefaultAsync(r =>
                r.Id == joinRequestId && r.ToUserId == _userProvider.UserId);
        
        if (isJoin)
        {
            var userScience = new UserScience()
            {
                ScienceId = joinRequest.ScienceId,
                UserId = joinRequest.ToUserId,
                Type = IdentityData.Enums.UserScience.Student
            };
            joinRequest.IsJoined = true;
            _context.UserSciences.Add(userScience);
        }
        else
        {
            _context.SendRequestToJoins.Remove(joinRequest!);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Profile", "User");
    } 




}

Full_Identity/Views/School/CreateSchool.cshtml
@model Full_Identity.DTOs.CreateSchoolDTO
<h1>Create school</h1>
<form class="row g-3" style="width: 400px" asp-controller="School" asp-action="CreateSchool" enctype="multipart/form-data" method="post">
    <div>
        <input  name="Name" class="form-control" asp-for="Name" type="text" placeholder="Name"/>
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input  name="Description" class="form-control" asp-for="Description" type="text" placeholder="Description"/>
        <span asp-validation-for="Description"></span>
    </div>  
     <div>
           <input name="Photo" class="form-control" asp-for="Photo" type="file" />
           <span asp-validation-for="Photo"></span>
       </div>
    <button class="form-control"  type="submit" >Add</button>
</form>

Full_Identity/Views/School/GetSchoolById.cshtml
@using IdentityData.Enums
@using Full_Identity.Helper
@model IdentityData.Entities.School
@inject UserProvider UserProvider
<h1> School Name: @Model.Name</h1>
<h1> School Description: @Model.Description</h1>
<h1>Creator: @Model.UserSchools.First(user=> user.Status ==UserStatus.Creator).User.FirstName</h1>
<a class="btn btn-primary" asp-controller="Science" asp-action="Index" asp-route-Id="@Model.Id" >Sciences</a>
<partial name="JoinClass" />
<partial name="UpdateSchoolLink" />
<h3>School</h3>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">FirstName</th>
        <th scope="col">LastName</th>
        <th scope="col">Number of Users</th>
    </tr>
    </thead>
    <tbody>
    @{
        int i = 0;
    }
               @{
                   var userId = Model.UserSchools.FirstOrDefault(i => i.UserId == UserProvider.UserId);
               }
    
    @foreach (var model in Model.UserSchools)
    {
        i++;
        <tr>
            <th scope="row">@(i)</th>
            <td>@(model.User.FirstName)</td>
            <td>@(model.User.LastName)</td>
            @{
                if ((model.UserId != UserProvider.UserId && model.Status != UserStatus.Creator )&&  (userId.Status == UserStatus.Admin || userId.Status == UserStatus.Creator))
                {     <td>
                          <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                              <div class="btn-group" role="group"></div>
                              <button type="button" class="btn btn-primary dropdown dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                  @(model.Status)
                              </button>
                              <div class="dropdown-menu">
                                  <li> <a class="dropdown-item" asp-controller="School" asp-action="UpdateRole" asp-route-userId="@(model.UserId)" asp-route-schoolId="@(model.SchoolId)" asp-route-status="@UserStatus.Admin"  >Admin</a></li>
                                  <li> <a class="dropdown-item" asp-controller="School" asp-action="UpdateRole" asp-route-userId="@(model.UserId)" asp-route-schoolId="@(model.SchoolId)" asp-route-status="@UserStatus.Teacher" >Teacher</a></li>
                                  <li> <a class="dropdown-item" asp-controller="School" asp-action="UpdateRole" asp-route-userId="@(model.UserId)" asp-route-schoolId="@(model.SchoolId)" asp-route-status="@UserStatus.Student" >Student</a></li>
                              </div>
                          </div>  
                      </td>
                }
                else
                {
                    <td>@(model.Status)</td>
                }
            }
            
        </tr>
    }
    </tbody>
</table>

Full_Identity/Views/School/Index.cshtml
@model List<IdentityData.Entities.School>


<h1>List of Schools</h1>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Number of Users</th>
    </tr>
    </thead>
    <tbody>
    @{
        int i = 0;
    }
    @foreach (var model in Model)
    {
        i++;
        <tr>
            <th scope="row">@(i)</th>
            <td>@(model.Name)</td>
            <td>@(model.Description)</td>
            <td>@(model.UserSchools.Count)</td>
            <td>
                <a class="btn btn-primary" asp-action="GetSchoolById" asp-route-id="@(model.Id)">View</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Full_Identity/Views/School/UpdateSchool.cshtml
@model Full_Identity.DTOs.UpdataScoolDTO

<h1>Update Science</h1>
<form class="row g-3" style="width: 400px" asp-controller="School" 
      asp-action="UpdateSchool" 
      asp-route-Id="@ViewBag.Id"
      enctype="multipart/form-data" method="post">
    <div>
        <input  name="Name" class="form-control" asp-for="Name" type="text" placeholder="Name"/>
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input  name="Description" class="form-control" asp-for="Description" type="text" placeholder="Description"/>
        <span asp-validation-for="Description"></span>
    </div>  
    <div>
        <input name="Photo" class="form-control" asp-for="Photo" type="file" />
        <span asp-validation-for="Photo"></span>
    </div>
    <button class="form-control"  type="submit" >Add</button>
</form>