Full_Identity/Controllers/ScienceController.cs
using Full_Identity.DTOs;
using Full_Identity.Helper;
using IdentityData.AppDbContext;
using IdentityData.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Full_Identity.Controllers;

public class ScienceController : Controller
{
    private readonly Context _context;
    private readonly UserProvider _userProvider;

    public ScienceController(Context context, UserProvider userProvider)
    {
        _context = context;
        _userProvider = userProvider;
    }

    public async Task<IActionResult> Index(Guid Id)
    {
     
        var school = await _context.Schools.
            Include(s => s.Sciences!)
            .ThenInclude(o => o.UserSciences).FirstOrDefaultAsync(k => k.Id == Id);
        return View(school);
    }

    [HttpGet]
    public IActionResult CreateScience(Guid Id)
    {
        ViewBag.Id = Id;
        return View();
    } 
    
    [HttpPost]
    public async Task<IActionResult> CreateScience(CreateScienceDTO createScienceDto,Guid schoolId)
    {
        var userId = _userProvider.UserId;
        var science = new Science()
        {
            SchoolId = schoolId,
            Name = createScienceDto.Name,
            Description = createScienceDto.Description,
        };
        
        science.UserSciences = new List<UserScience>()
        {
            new UserScience()
            {
                UserId = userId,
                Type = IdentityData.Enums.UserScience.Teacher,

            }
        };
        _context.Sciences.Add(science);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index",new{ Id = schoolId});
    }

    public async Task<IActionResult> GetScienceById(Guid Id)
    {
        var science = await _context.Sciences
            .Include(i => i.UserSciences)!.
            ThenInclude(i => i.User).
            ThenInclude(t=>t.UserSchools).Include(i=>i.School).
            FirstOrDefaultAsync(i => i.Id == Id);
        
        
        return View(science);
    }
    [HttpGet]
    public async Task<IActionResult> UpdateScience(Guid Id)
    {
        var science = await _context.Sciences.FirstOrDefaultAsync(i => i.Id == Id);
        ViewBag.Id = Id;
        return View(new UpdateScienceDTO()
        {
            Name = science.Name,
            Description = science.Description,
        });
    }

    [HttpPost]
    public async Task<IActionResult> UpdateScience(Guid Id, [FromForm] UpdateScienceDTO updateScienceDto)
    {
        var science =  await _context.Sciences.FirstOrDefaultAsync(i => i.Id == Id);
        science.Name = updateScienceDto.Name;
        science.Description = updateScienceDto.Description;

        await _context.SaveChangesAsync();
        return RedirectToAction("GetScienceById", new { id = science.Id });
    }

    [HttpGet]
    public IActionResult RequestToJoin(Guid Id)
    {
        ViewBag.Id = Id;
        return View();
    }
  [HttpPost]
    public async Task<IActionResult> RequestToJoin(Guid Id, CreateRequestToJoin createRequestToJoin)
    {
        var toUser = await _context.Users.
            FirstOrDefaultAsync(i => i.UserName == createRequestToJoin.Username);
        var isExist = await _context.SendRequestToJoins.
            AnyAsync(i => i.ToUserId ==toUser!.Id  && i.ScienceId == Id);
        if (isExist)
        {
            return RedirectToAction("GetScienceById", new { id = Id });
        }
        var userId = _userProvider.UserId;

        var request = new SendRequestToJoin()
        {
            FromWhomId = userId,
            ScienceId = Id,
            ToUserId = toUser.Id,
            IsJoined = false
        };
        _context.SendRequestToJoins.Add(request);
        await _context.SaveChangesAsync();
        return RedirectToAction("GetScienceById", new { id = Id });
    }

    public async Task<IActionResult> JoinScience(Guid joinRequestId,bool isJoin)
    {
        var joinRequest = await _context.SendRequestToJoins.FirstOrDefaultAsync(r =>
                r.Id == joinRequestId && r.ToUserId == _userProvider.UserId);
        
        if (isJoin)
        {
            var userScience = new UserScience()
            {
                ScienceId = joinRequest.ScienceId,
                UserId = joinRequest.ToUserId,
                Type = IdentityData.Enums.UserScience.Student
            };
            joinRequest.IsJoined = true;
            _context.UserSciences.Add(userScience);
        }
        else
        {
            _context.SendRequestToJoins.Remove(joinRequest!);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction("Profile", "User");
    } 




}

Full_Identity/Controllers/TaskController.cs
using Full_Identity.DTOs;
using Full_Identity.Helper;
using IdentityData.AppDbContext;
using IdentityData.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Full_Identity.Controllers;

public class TaskController : Controller
{
    private readonly Context _context;
    private readonly UserProvider UserProvider;

        public TaskController(Context context, UserProvider userProvider)
        {
            _context = context;
            UserProvider = userProvider;
        }
    public async Task<IActionResult> Index(Guid scienceId)
    {
        
        var tasks = await _context.TaskEntities.
            Where(i=>i.ScienceId ==scienceId)
            .ToListAsync();
        ViewBag.ScienceId = scienceId;
        return View(tasks);
    }

    [HttpGet]
    public IActionResult AddTask(Guid scienceId)
    {
        ViewBag.ScienceId = scienceId;
        return View();
    }   
    [HttpPost]
    public async Task<IActionResult> AddTask(Guid scienceId,[FromForm] CreateTaskDto createTaskDto)
    {
        var task = new TaskEntity()
        {
            Title = createTaskDto.Title,
            Description = createTaskDto.Description,
            CreatedDate = createTaskDto.CreatedDate,
            StartDate = createTaskDto.StartDate,
            EndDate = createTaskDto.EndDate,
            ScienceId = scienceId,
            Status = TaskStatus.Created,
            MaxBall = createTaskDto.MaxBall,
        };
        _context.TaskEntities.Add(task);
        await _context.SaveChangesAsync();
        
        return RedirectToAction("Index", new { scienceId = scienceId });
    }

    public Task<IActionResult> GetById(Guid taskId)
    {
        var task =  _context.TaskEntities.Include(y=>y.TaskComments).ThenInclude(i=>i.User).FirstOrDefault(i => i.Id == taskId)!;
        return Task.FromResult<IActionResult>(View(task));
    }

    public async Task<IActionResult> AddComment(Guid taskId,[FromForm] CreateComment createComment)
    {
        var comment = new TaskComment()
        {
            Message = createComment.Comment,
            TaskId = taskId,
            UserId = UserProvider.UserId
        };
        _context.TaskComments.Add(comment);
        await _context.SaveChangesAsync();
        return RedirectToAction("GetById", new { taskId });
    }
}

Full_Identity/Views/Science/CreateScience.cshtml
@model Full_Identity.DTOs.CreateScienceDTO

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<h1>Add Science</h1>
<form class="row g-3" style="width: 400px" asp-controller="Science" asp-action="CreateScience" asp-route-schoolId="@ViewBag.Id" method="post">
    <div>
        <input  name="Name" class="form-control" asp-for="Name" type="text" placeholder="Name"/>
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input  name="Description" class="form-control" asp-for="Description" type="text" placeholder="Description"/>
        <span asp-validation-for="Description"></span>
    </div>
    <button class="form-control"  type="submit" >Add</button>
</form>

Full_Identity/Views/Science/GetScienceById.cshtml
@using IdentityData.Enums
@model IdentityData.Entities.Science 
<partial name="UpdateScience12" />

<a class="btn btn-primary" asp-action="RequestToJoin" asp-controller="Science" asp-route-Id="@(Model.Id)">Send Request to Join</a>

<a class="btn btn-primary" asp-controller="Task" asp-action="Index" asp-route-scienceId="@Model.Id">Tasks</a>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Role</th>
    </tr>
    </thead>
    <tbody>
    @{
        int i = 0;
    }
    @foreach (var model in Model.UserSciences!)
    {
        i++;
        <tr>
            <th scope="row">@(i)</th>
            <td>@(model.User.FirstName)</td>
            <td>@(model.User.LastName)</td>
            <td>@(model.Type)</td>
        </tr>
    }
    </tbody>
</table>

Full_Identity/Views/Science/Index.cshtml
@using IdentityData.AppDbContext
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Full_Identity.Helper
@using Microsoft.EntityFrameworkCore
@model IdentityData.Entities.School
@inject Context Context
@inject UserProvider UserProvider  
<a class="btn btn-primary" asp-action="CreateScience" asp-controller="Science" asp-route-Id="@Model.Id">Create</a>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Number of Sciences </th>
    </tr>
    </thead>
    <tbody>
    @{
        int i = 0;
    }
    @foreach (var model in Model.Sciences)
    {
        i++;
        <tr>
            <th scope="row">@(i)</th>
            <td>@(model.Name)</td>
            <td>@(model.Description)</td>
            <td>
                <a class="btn btn-primary" asp-action="GetScienceById" asp-route-id="@(model.Id)">View</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Full_Identity/Views/Science/RequestToJoin.cshtml
@model Full_Identity.DTOs.CreateRequestToJoin

@{
    ViewData["Title"] = "Send Join Science Request";
}

<h1 style="margin: auto; text-align: center">Send Join Science Request</h1>
<form class="row g-3" style="width: 400px; margin: auto"  asp-action="RequestToJoin" asp-route-Id="@ViewBag.Id" method="post">
    <div>
        <input name="Username" class="form-control" asp-for="Username" type="text" placeholder="Username" />
        <span class="text-danger" asp-validation-for="Username"></span>
    </div>
    <button class="form-control" type="submit">Send join request</button>
</form>

Full_Identity/Views/Science/UpdateScience.cshtml
@model Full_Identity.DTOs.UpdateScienceDTO


<h1>Update school</h1>
<form class="row g-3" style="width: 400px" asp-controller="Science" 
      asp-action="UpdateScience" 
      asp-route-Id="@ViewBag.Id"
      enctype="multipart/form-data" method="post">
    <div>
        <input  name="Name" class="form-control" asp-for="Name" type="text" placeholder="Name"/>
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input  name="Description" class="form-control" asp-for="Description" type="text" placeholder="Description"/>
        <span asp-validation-for="Description"></span>
    </div>
    <button class="form-control"  type="submit" >Add</button>
</form>